services:
  db:
    image: mysql:8.0
    container_name: recipe_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recipe_book
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - recipe_db:/var/lib/mysql

volumes:
  recipe_db:
